version: "3.9"

services:
  server:
    container_name: server
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "pnpm run dev"
    environment:
      DB_URI: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@db:$MONGO_LOCAL_PORT/$MONGO_DATABASE?authSource=admin
      PORT: $SERVER_LOCAL_PORT
      NODE_ENV: development
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_REMOTE_PORT
    volumes:
      - .:/usr/src/app
    links:
      - db
  db:
    container_name: db
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_REMOTE_PORT
    restart: always
    volumes:
      - data:/data/db
volumes:
  data:
  